# TORCH.TENSOR
(more info https://pytorch.org/docs/stable/tensors.html#torch.Tensor)

A torch.Tensor is a multi-dimensional matrix containing elements of a single data type. The tensor is one of the most important data structures in PyTorch because it represent all the parts of our models and data. Such as the model weights ($w$), biases ($b$), input ($x$), ground truth ($y$), etc.

In this class we will learn some basic operations with tensors:

- Creating Tensors
- Tensor Properties and Attributes
- Device Placement
- Conversion to/from NumPy
- Basic Operations
- Indexing and Slicing
- Reshaping Tensors
- Reduction Operations
- Matrix Operations
- Concatenation and Stacking

### - - Needed imports - - 

use  **pip install lightning**  to install the dependences

In [1]:
import torch 
import numpy as np

### **__Step 1__:** Creating Tensors

##### Creating a tensor from a python list

In [2]:
data_list = [1, 2, 3]
tensor_from_list = torch.tensor(data_list)


tensor_from_list

tensor([1, 2, 3])

Getting the tensor back as a list

In [3]:
tensor_from_list.tolist()

[1, 2, 3]

##### Creating a tensor from a NumPy array

In [4]:
data_numpy = np.array([4.0, 5.0, 6.0])
tensor_from_numpy = torch.tensor(data_numpy)


tensor_from_numpy

tensor([4., 5., 6.], dtype=torch.float64)

##### Creating a tensor of zeros and ones with specified shape

In [5]:
zeros_tensor = torch.zeros(2, 3)  # 2 rows, 3 columns
ones_tensor = torch.ones((4, 2, 3, 5))   # 3 rows, 2 columns

print("Zeros tensor:\n", zeros_tensor)
print("Ones tensor:\n", ones_tensor)

Zeros tensor:
 tensor([[0., 0., 0.],
        [0., 0., 0.]])
Ones tensor:
 tensor([[[[1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.]],

         [[1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.]]],


        [[[1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.]],

         [[1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.]]],


        [[[1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.]],

         [[1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.]]],


        [[[1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.]],

         [[1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.]]]])


##### Creating a tensor with random values between 0 and 1

In [6]:
random_tensor = torch.rand(3, 3)  # 3 rows, 3 columns


random_tensor

tensor([[0.2132, 0.9655, 0.0709],
        [0.7331, 0.8785, 0.8298],
        [0.2293, 0.2478, 0.0179]])


##### Creating tensors with specific data types and on GPU

In [7]:

# Creating tensors with specific data types (by default it creates the tensor in the CPU memory)
int_tensor = torch.tensor([1, 2, 3], dtype=torch.int)
float_tensor = torch.tensor([1.0, 2.0, 3.0], dtype=torch.float)

# Creating tensors on GPU
cuda_tensor = torch.tensor([1, 2, 3], device='cuda')

print("Integer tensor:", int_tensor)
print("Float tensor:", float_tensor)
print("CUDA tensor:", cuda_tensor)

Integer tensor: tensor([1, 2, 3], dtype=torch.int32)
Float tensor: tensor([1., 2., 3.])
CUDA tensor: tensor([1, 2, 3], device='cuda:0')


### **Step 2:** Placing a Tensor in diferent devices

##### Moving a tensor to GPU (if available)

In [8]:
# Creating a tensor on CPU
cpu_tensor = torch.tensor([1.0, 2.0, 3.0])

if torch.cuda.is_available():
    gpu_tensor = cpu_tensor.to('cuda')
    print("Tensor on GPU:", gpu_tensor)
else:
    print("GPU not available.")

cpu_again = gpu_tensor.to('cpu')
print("Tensor on CPU again:", cpu_again)

Tensor on GPU: tensor([1., 2., 3.], device='cuda:0')
Tensor on CPU again: tensor([1., 2., 3.])


##### We can also use .cpu() and .cuda() 

In [9]:
# Creating a tensor on CPU
cpu_tensor = torch.tensor([1.0, 2.0, 3.0])

if torch.cuda.is_available():
    gpu_tensor = cpu_tensor.cuda()
    print("Tensor on GPU:", gpu_tensor)
else:
    print("GPU not available.")

cpu_again = gpu_tensor.cpu()
print("Tensor on CPU again:", cpu_again)

Tensor on GPU: tensor([1., 2., 3.], device='cuda:0')
Tensor on CPU again: tensor([1., 2., 3.])


### **Step 3:** Tensor Properties and Attributes

In [10]:
# Creating a tensor
tensor = torch.tensor([[1, 2, 3],
                       [4, 5, 6]])

print("Tensor Properties:")
print("- Shape:", tensor.shape) # gets a list with each dimension size in the tensor
print("- Data Type:", tensor.dtype) # gets the type of the tensor 
print("- Device:", tensor.device) # gets the device where the tensor is placed
print("- Number of Dimensions (Rank):", tensor.ndim) # gets the number of dimenssions of the tensor

Tensor Properties:
- Shape: torch.Size([2, 3])
- Data Type: torch.int64
- Device: cpu
- Number of Dimensions (Rank): 2


### **Step 4:** Conversion to/from NumPy

##### Converting tensors to NumPy arrays

In [11]:
tensor = torch.tensor([1.0, 2.0, 3.0])
numpy_array = tensor.numpy()

print("Tensor to NumPy:")
print("Original Tensor:", tensor)
print("Converted NumPy Array:", numpy_array)

Tensor to NumPy:
Original Tensor: tensor([1., 2., 3.])
Converted NumPy Array: [1. 2. 3.]


##### Converting NumPy arrays to tensors

In [12]:

numpy_arr = np.array([4.0, 5.0, 6.0])
tensor_from_numpy = torch.from_numpy(numpy_arr)

print("NumPy to Tensor:")
print("Original NumPy Array:", numpy_arr)
print("Converted Tensor:", tensor_from_numpy)

NumPy to Tensor:
Original NumPy Array: [4. 5. 6.]
Converted Tensor: tensor([4., 5., 6.], dtype=torch.float64)


### **Step 5:** Basic Operations

In [13]:
# Creating example tensors
tensor1 = torch.tensor([[1, 2, 3],
                        [4, 5, 6]])

tensor2 = torch.tensor([[2, 3, 4],
                        [5, 6, 7]])

##### Basic element-wise operations

In [14]:
print("Basic Element-Wise Operations:")
print("- Addition:\n", tensor1 + tensor2)
print("- Subtraction:\n", tensor1 - tensor2)
print("- Multiplication:\n", tensor1 * tensor2)
print("- Division:\n", tensor1 / tensor2)

Basic Element-Wise Operations:
- Addition:
 tensor([[ 3,  5,  7],
        [ 9, 11, 13]])
- Subtraction:
 tensor([[-1, -1, -1],
        [-1, -1, -1]])
- Multiplication:
 tensor([[ 2,  6, 12],
        [20, 30, 42]])
- Division:
 tensor([[0.5000, 0.6667, 0.7500],
        [0.8000, 0.8333, 0.8571]])


##### Broadcasting for element-wise operations

In [15]:
print("Broadcasting:")
scalar = 10
result = tensor1 * scalar
print("Adding scalar to tensor:\n", result)

Broadcasting:
Adding scalar to tensor:
 tensor([[10, 20, 30],
        [40, 50, 60]])


##### Introducing common mathematical functions

In [16]:
print("Common Mathematical Functions:")
exponential = torch.exp(tensor1)
square_root = torch.sqrt(tensor2)
print("- Exponential:\n", exponential)
print("- Square Root:\n", square_root)

Common Mathematical Functions:
- Exponential:
 tensor([[  2.7183,   7.3891,  20.0855],
        [ 54.5981, 148.4132, 403.4288]])
- Square Root:
 tensor([[1.4142, 1.7321, 2.0000],
        [2.2361, 2.4495, 2.6458]])


### **Step 6:** Indexing and Slicing

In [17]:

# Creating a tensor
tensor = torch.tensor([[1, 2, 3],
                       [4, 5, 6],
                       [7, 8, 9]])

# Indexing and slicing
print("Indexing and Slicing:")
print("- Element at [1, 1]:", tensor[1, 1])
print("- First row:", tensor[0])
print("- Second column:", tensor[:, 1])
print("- Sub-tensor (top-left 2x2):\n", tensor[1:3, 1:3])
print()

# Negative indices and strides
print("Negative Indices and Strides:")
print("- Last element:", tensor[-1, -2])
print("- Every second row:\n", tensor[::2, ::2])

Indexing and Slicing:
- Element at [1, 1]: tensor(5)
- First row: tensor([1, 2, 3])
- Second column: tensor([2, 5, 8])
- Sub-tensor (top-left 2x2):
 tensor([[5, 6],
        [8, 9]])

Negative Indices and Strides:
- Last element: tensor(8)
- Every second row:
 tensor([[1, 3],
        [7, 9]])


##### **Step 7:** Reshaping Tensors

In [18]:
tensor = torch.tensor([[1, 2, 3],
                       [4, 5, 6]])

tensor

tensor([[1, 2, 3],
        [4, 5, 6]])

##### Reshaping with .view()

In [19]:
reshaped_view = tensor.view(3, 2)
print("Reshaped with .view():\n", reshaped_view)

Reshaped with .view():
 tensor([[1, 2],
        [3, 4],
        [5, 6]])


##### Reshaping with .reshape()

In [20]:
reshaped_reshape = tensor.reshape(1, 6)
print("Reshaped with .reshape():\n", reshaped_reshape)

Reshaped with .reshape():
 tensor([[1, 2, 3, 4, 5, 6]])


##### using -1 as shape

In [21]:
reshaped = tensor.view(3, -1)
print("Reshaped:\n", reshaped)


Reshaped:
 tensor([[1, 2],
        [3, 4],
        [5, 6]])


### **Step 8:** Reduction Operations

#### Reduction operations over all dims

In [22]:
# Creating a tensor
tensor = torch.tensor([[1, 2, 3],
                       [4, 5, 6]], 
                       dtype=torch.float)

# Reduction operations
print("Reduction Operations:")
print("- Sum:", tensor.sum())
print("- Mean:", tensor.mean())
print("- Standard Deviation:", tensor.float().std())
print("- Maximum:", tensor.max())

Reduction Operations:
- Sum: tensor(21.)
- Mean: tensor(3.5000)
- Standard Deviation: tensor(1.8708)
- Maximum: tensor(6.)


##### Reduction along specific dimensions

In [23]:
tensor_2d = torch.tensor([[1, 2, 3],
                          [4, 5, 6],
                          [7, 8, 9]]).float()

# Sum along rows (dim=0)
sum_along_rows = tensor_2d.sum(dim=1)
print("Sum along rows (dim=0):\n", sum_along_rows)

# Mean along columns (dim=1)
mean_along_columns = tensor_2d.mean(dim=1)
print("Mean along columns (dim=1):\n", mean_along_columns)

Sum along rows (dim=0):
 tensor([ 6., 15., 24.])
Mean along columns (dim=1):
 tensor([2., 5., 8.])


### **Step 9:** Matrix Operations

In [24]:
# Creating example tensors
matrix1 = torch.tensor([[1, 2],
                        [3, 4]])

matrix2 = torch.tensor([[5, 6],
                        [7, 8]])

##### Matrix multiplication

In [25]:
print("Matrix Multiplication:")
matrix_product = torch.mm(matrix1, matrix2)
print("Matrix Product (torch.mm()):\n", matrix_product)

Matrix Multiplication:
Matrix Product (torch.mm()):
 tensor([[19, 22],
        [43, 50]])


##### Matrix multiplication with torch.matmul()

In [26]:
matrix_product_matmul = torch.matmul(matrix1, matrix2)
print("Matrix Product (torch.matmul()):\n", matrix_product_matmul)

Matrix Product (torch.matmul()):
 tensor([[19, 22],
        [43, 50]])


##### Matrix multiplication with  @ operator

In [27]:
matrix_product_matmul = matrix1 @ matrix2
print("Matrix Product with @ operator\n", matrix_product_matmul)

Matrix Product with @ operator
 tensor([[19, 22],
        [43, 50]])


##### Transposition


In [28]:

matrix_transpose = matrix1.T
print("Transposed Matrix:\n", matrix_transpose)

Transposed Matrix:
 tensor([[1, 3],
        [2, 4]])


##### Determinant

In [29]:

matrix3 = torch.tensor([[1, 2, 3],
                        [4, 5, 6],
                        [7, 8, 9]]).float()
determinant = torch.det(matrix3)
print("Determinant:\n", determinant)


Determinant:
 tensor(0.)


### **Step 10:** Concatenation and Stacking

In [30]:
# Creating example tensors
tensor1 = torch.tensor([[1, 2],
                        [3, 4]])

tensor2 = torch.tensor([[5, 6],
                        [7, 8]])

##### Concatenation using torch.cat()

In [31]:
concatenated_rows    = torch.cat((tensor1, tensor2), dim=0)
concatenated_columns = torch.cat((tensor1, tensor2), dim=1)

print("Concatenation using torch.cat():")
print("Concatenated Rows:\n", concatenated_rows)
print("Concatenated Columns:\n", concatenated_columns)

Concatenation using torch.cat():
Concatenated Rows:
 tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])
Concatenated Columns:
 tensor([[1, 2, 5, 6],
        [3, 4, 7, 8]])


##### Stacking using torch.stack()

In [32]:
stacked_tensors = torch.stack((tensor1, tensor2, tensor1, tensor2))

print("Stacking using torch.stack():")
print("Stacked Tensors:\n", stacked_tensors)
print("Stacked Tensors shape:\n", stacked_tensors.shape)

Stacking using torch.stack():
Stacked Tensors:
 tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]],

        [[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])
Stacked Tensors shape:
 torch.Size([4, 2, 2])


### **Step 11:** Adding or removing dimenssions to a tensor

##### Ading a dimenssion to a tensor with .unsqueeze()

In [33]:
tensor = torch.tensor([[1, 2],
                        [3, 4]])

print("Tensor size before unsqueeze:\n", tensor.shape)

tensor = tensor.unsqueeze(1)
print("Tensor after unsqueeze:\n", tensor)
print("Tensor size after unsqueeze:\n", tensor.shape)


Tensor size before unsqueeze:
 torch.Size([2, 2])
Tensor after unsqueeze:
 tensor([[[1, 2]],

        [[3, 4]]])
Tensor size after unsqueeze:
 torch.Size([2, 1, 2])


##### Removing dimenssions with size=1 from a tensor with .squeeze()

In [34]:
print("Tensor size before squeeze:\n", tensor.shape)
tensor = tensor.squeeze()
print("Tensor after unsqueeze:\n", tensor)
print("Tensor size after unsqueeze:\n", tensor.shape)

Tensor size before squeeze:
 torch.Size([2, 1, 2])
Tensor after unsqueeze:
 tensor([[1, 2],
        [3, 4]])
Tensor size after unsqueeze:
 torch.Size([2, 2])
